// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moto_Shop.Data;

namespace Moto_Shop.Migrations
{
    [DbContext(typeof(MotoDBContext))]
    [Migration("20201230142325_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Moto_Shop.Data.Models.ModelMotorcycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Class");

                    b.Property<byte>("Cylinders");

                    b.Property<string>("DriveUnit");

                    b.Property<int>("EngineVolume");

                    b.Property<string>("FrontTires");

                    b.Property<string>("FuelSupplySystem");

                    b.Property<byte>("FuelTank");

                    b.Property<byte>("HorsePower");

                    b.Property<int>("MaxSpeed");

                    b.Property<string>("ModelName");

                    b.Property<string>("RearTires");

                    b.Property<byte>("Ticks");

                    b.Property<string>("Transmission");

                    b.HasKey("Id");

                    b.ToTable("MotoModel");
                });

            modelBuilder.Entity("Moto_Shop.Data.Models.Motorcycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Avialable");

                    b.Property<string>("Color");

                    b.Property<string>("Image");

                    b.Property<bool>("IsFavorite");

                    b.Property<string>("LongDesc");

                    b.Property<string>("Manufacturer");

                    b.Property<int>("Mileage");

                    b.Property<int>("ModelID");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<string>("ShortDesc");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.HasIndex("ModelID");

                    b.ToTable("Moto");
                });

            modelBuilder.Entity("Moto_Shop.Data.Models.Motorcycle", b =>
                {
                    b.HasOne("Moto_Shop.Data.Models.ModelMotorcycle", "Model")
                        .WithMany("Moto")
                        .HasForeignKey("ModelID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
